export * from './admin.service';
import { AdminProvider } from './admin.service';
export * from './admin.serviceInterface';
export * from './app-user.service';
import { AppUserProvider } from './app-user.service';
export * from './app-user.serviceInterface';
export * from './bad-debt-case.service';
import { BadDebtCaseProvider } from './bad-debt-case.service';
export * from './bad-debt-case.serviceInterface';
export * from './cash-voucher.service';
import { CashVoucherProvider } from './cash-voucher.service';
export * from './cash-voucher.serviceInterface';
export * from './collaborator.service';
import { CollaboratorProvider } from './collaborator.service';
export * from './collaborator.serviceInterface';
export * from './custom-role.service';
import { CustomRoleProvider } from './custom-role.service';
export * from './custom-role.serviceInterface';
export * from './customer.service';
import { CustomerProvider } from './customer.service';
export * from './customer.serviceInterface';
export * from './customer-document.service';
import { CustomerDocumentProvider } from './customer-document.service';
export * from './customer-document.serviceInterface';
export * from './customer-source.service';
import { CustomerSourceProvider } from './customer-source.service';
export * from './customer-source.serviceInterface';
export * from './customer-visit.service';
import { CustomerVisitProvider } from './customer-visit.service';
export * from './customer-visit.serviceInterface';
export * from './insurance-contract.service';
import { InsuranceContractProvider } from './insurance-contract.service';
export * from './insurance-contract.serviceInterface';
export * from './loan-charge.service';
import { LoanChargeProvider } from './loan-charge.service';
export * from './loan-charge.serviceInterface';
export * from './loan-collateral.service';
import { LoanCollateralProvider } from './loan-collateral.service';
export * from './loan-collateral.serviceInterface';
export * from './loan-contract.service';
import { LoanContractProvider } from './loan-contract.service';
export * from './loan-contract.serviceInterface';
export * from './loan-contract-attachment.service';
import { LoanContractAttachmentProvider } from './loan-contract-attachment.service';
export * from './loan-contract-attachment.serviceInterface';
export * from './loan-contract-document.service';
import { LoanContractDocumentProvider } from './loan-contract-document.service';
export * from './loan-contract-document.serviceInterface';
export * from './loan-product.service';
import { LoanProductProvider } from './loan-product.service';
export * from './loan-product.serviceInterface';
export * from './loan-settlement.service';
import { LoanSettlementProvider } from './loan-settlement.service';
export * from './loan-settlement.serviceInterface';
export * from './policy-setting.service';
import { PolicySettingProvider } from './policy-setting.service';
export * from './policy-setting.serviceInterface';
export * from './report.service';
import { ReportProvider } from './report.service';
export * from './report.serviceInterface';
export * from './role-permission.service';
import { RolePermissionProvider } from './role-permission.service';
export * from './role-permission.serviceInterface';
export * from './store.service';
import { StoreProvider } from './store.service';
export * from './store.serviceInterface';
export const APIS = [AdminProvider, AppUserProvider, BadDebtCaseProvider, CashVoucherProvider, CollaboratorProvider, CustomRoleProvider, CustomerProvider, CustomerDocumentProvider, CustomerSourceProvider, CustomerVisitProvider, InsuranceContractProvider, LoanChargeProvider, LoanCollateralProvider, LoanContractProvider, LoanContractAttachmentProvider, LoanContractDocumentProvider, LoanProductProvider, LoanSettlementProvider, PolicySettingProvider, ReportProvider, RolePermissionProvider, StoreProvider];
