/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CUAppUserModel } from '../model/models';
import { ResultAPI } from '../model/models';
import { SearchAppUserRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AppUserServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/AppUser/GetAll
     */
    apiAppUserGetAllGet(extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/AppUser/GetById
     * @param body 
     */
    apiAppUserGetByIdPost(body?: string, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/AppUser/Save
     * @param cUAppUserModel 
     */
    apiAppUserSavePost(cUAppUserModel?: CUAppUserModel, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/AppUser/Search
     * @param searchAppUserRequest 
     */
    apiAppUserSearchPost(searchAppUserRequest?: SearchAppUserRequest, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
