/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CUBadDebtCaseModel } from '../model/models';
import { RecordBadDebtRecoveryModel } from '../model/models';
import { ResultAPI } from '../model/models';
import { SearchBadDebtCaseRequest } from '../model/models';
import { TransferBadDebtRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiBadDebtCaseGetByIdPostRequestParams {
    body?: string;
}

export interface ApiBadDebtCaseRecordRecoveryPostRequestParams {
    recordBadDebtRecoveryModel?: RecordBadDebtRecoveryModel;
}

export interface ApiBadDebtCaseSavePostRequestParams {
    cUBadDebtCaseModel?: CUBadDebtCaseModel;
}

export interface ApiBadDebtCaseSearchPostRequestParams {
    searchBadDebtCaseRequest?: SearchBadDebtCaseRequest;
}

export interface ApiBadDebtCaseTransferFromLoanPostRequestParams {
    transferBadDebtRequest?: TransferBadDebtRequest;
}


export interface BadDebtCaseProviderInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/BadDebtCase/GetAll
*/
    apiBadDebtCaseGetAllGet(extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/BadDebtCase/GetById
* @param requestParameters
     */
    apiBadDebtCaseGetByIdPost(requestParameters: ApiBadDebtCaseGetByIdPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/BadDebtCase/RecordRecovery
* @param requestParameters
     */
    apiBadDebtCaseRecordRecoveryPost(requestParameters: ApiBadDebtCaseRecordRecoveryPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/BadDebtCase/Save
* @param requestParameters
     */
    apiBadDebtCaseSavePost(requestParameters: ApiBadDebtCaseSavePostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/BadDebtCase/Search
* @param requestParameters
     */
    apiBadDebtCaseSearchPost(requestParameters: ApiBadDebtCaseSearchPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/BadDebtCase/TransferFromLoan
* @param requestParameters
     */
    apiBadDebtCaseTransferFromLoanPost(requestParameters: ApiBadDebtCaseTransferFromLoanPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
