/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CUCashVoucherModel } from '../model/models';
import { CollectLoanPaymentModel } from '../model/models';
import { ResultAPI } from '../model/models';
import { SearchCashVoucherRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiCashVoucherCollectLoanPaymentPostRequestParams {
    collectLoanPaymentModel?: CollectLoanPaymentModel;
}

export interface ApiCashVoucherGetByIdPostRequestParams {
    body?: string;
}

export interface ApiCashVoucherGetByLoanContractPostRequestParams {
    body?: string;
}

export interface ApiCashVoucherSavePostRequestParams {
    cUCashVoucherModel?: CUCashVoucherModel;
}

export interface ApiCashVoucherSearchPostRequestParams {
    searchCashVoucherRequest?: SearchCashVoucherRequest;
}


export interface CashVoucherProviderInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/CashVoucher/CollectLoanPayment
* @param requestParameters
     */
    apiCashVoucherCollectLoanPaymentPost(requestParameters: ApiCashVoucherCollectLoanPaymentPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint get /api/CashVoucher/GetAll
*/
    apiCashVoucherGetAllGet(extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/CashVoucher/GetById
* @param requestParameters
     */
    apiCashVoucherGetByIdPost(requestParameters: ApiCashVoucherGetByIdPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/CashVoucher/GetByLoanContract
* @param requestParameters
     */
    apiCashVoucherGetByLoanContractPost(requestParameters: ApiCashVoucherGetByLoanContractPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/CashVoucher/Save
* @param requestParameters
     */
    apiCashVoucherSavePost(requestParameters: ApiCashVoucherSavePostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/CashVoucher/Search
* @param requestParameters
     */
    apiCashVoucherSearchPost(requestParameters: ApiCashVoucherSearchPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
