/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CUCashVoucherModel } from '../model/models';
import { ResultAPI } from '../model/models';
import { SearchCashVoucherRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CashVoucherServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/CashVoucher/GetAll
     */
    apiCashVoucherGetAllGet(extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/CashVoucher/GetById
     * @param body 
     */
    apiCashVoucherGetByIdPost(body?: string, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/CashVoucher/Save
     * @param cUCashVoucherModel 
     */
    apiCashVoucherSavePost(cUCashVoucherModel?: CUCashVoucherModel, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/CashVoucher/Search
     * @param searchCashVoucherRequest 
     */
    apiCashVoucherSearchPost(searchCashVoucherRequest?: SearchCashVoucherRequest, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
