/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ResultAPI } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiCustomerDocumentDownloadDocumentIdGetRequestParams {
    documentId: string;
}

export interface ApiCustomerDocumentGetByCustomerPostRequestParams {
    body?: string;
}

export interface ApiCustomerDocumentUploadPostRequestParams {
    customerId: string;
    file: Blob;
    documentType: string;
    note?: string;
}

export interface ApiCustomerDocumentViewDocumentIdGetRequestParams {
    documentId: string;
}


export interface CustomerDocumentProviderInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/CustomerDocument/Download/{documentId}
* @param requestParameters
     */
    apiCustomerDocumentDownloadDocumentIdGet(requestParameters: ApiCustomerDocumentDownloadDocumentIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/CustomerDocument/GetByCustomer
* @param requestParameters
     */
    apiCustomerDocumentGetByCustomerPost(requestParameters: ApiCustomerDocumentGetByCustomerPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/CustomerDocument/Upload
* @param requestParameters
     */
    apiCustomerDocumentUploadPost(requestParameters: ApiCustomerDocumentUploadPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint get /api/CustomerDocument/View/{documentId}
* @param requestParameters
     */
    apiCustomerDocumentViewDocumentIdGet(requestParameters: ApiCustomerDocumentViewDocumentIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
