/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AssignCustomerRequest } from '../model/models';
import { CUCustomerModel } from '../model/models';
import { ResultAPI } from '../model/models';
import { SearchCustomerRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiCustomerAssignPostRequestParams {
    assignCustomerRequest?: AssignCustomerRequest;
}

export interface ApiCustomerGetByIdPostRequestParams {
    body?: string;
}

export interface ApiCustomerGetByNationalIdPostRequestParams {
    body?: string;
}

export interface ApiCustomerSavePostRequestParams {
    cUCustomerModel?: CUCustomerModel;
}

export interface ApiCustomerSearchPostRequestParams {
    searchCustomerRequest?: SearchCustomerRequest;
}


export interface CustomerProviderInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/Customer/Assign
* @param requestParameters
     */
    apiCustomerAssignPost(requestParameters: ApiCustomerAssignPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint get /api/Customer/GetAll
*/
    apiCustomerGetAllGet(extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Customer/GetById
* @param requestParameters
     */
    apiCustomerGetByIdPost(requestParameters: ApiCustomerGetByIdPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Customer/GetByNationalId
* @param requestParameters
     */
    apiCustomerGetByNationalIdPost(requestParameters: ApiCustomerGetByNationalIdPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Customer/Save
* @param requestParameters
     */
    apiCustomerSavePost(requestParameters: ApiCustomerSavePostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Customer/Search
* @param requestParameters
     */
    apiCustomerSearchPost(requestParameters: ApiCustomerSearchPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
