/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CUInsuranceContractModel } from '../model/models';
import { ResultAPI } from '../model/models';
import { SearchInsuranceContractRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiInsuranceContractGetByIdPostRequestParams {
    body?: string;
}

export interface ApiInsuranceContractSavePostRequestParams {
    cUInsuranceContractModel?: CUInsuranceContractModel;
}

export interface ApiInsuranceContractSearchPostRequestParams {
    searchInsuranceContractRequest?: SearchInsuranceContractRequest;
}


export interface InsuranceContractProviderInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/InsuranceContract/GetAll
*/
    apiInsuranceContractGetAllGet(extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/InsuranceContract/GetById
* @param requestParameters
     */
    apiInsuranceContractGetByIdPost(requestParameters: ApiInsuranceContractGetByIdPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/InsuranceContract/Save
* @param requestParameters
     */
    apiInsuranceContractSavePost(requestParameters: ApiInsuranceContractSavePostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/InsuranceContract/Search
* @param requestParameters
     */
    apiInsuranceContractSearchPost(requestParameters: ApiInsuranceContractSearchPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
