/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CUInsuranceContractModel } from '../model/models';
import { ResultAPI } from '../model/models';
import { SearchInsuranceContractRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface InsuranceContractServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/InsuranceContract/GetAll
     */
    apiInsuranceContractGetAllGet(extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/InsuranceContract/GetById
     * @param body 
     */
    apiInsuranceContractGetByIdPost(body?: string, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/InsuranceContract/Save
     * @param cUInsuranceContractModel 
     */
    apiInsuranceContractSavePost(cUInsuranceContractModel?: CUInsuranceContractModel, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/InsuranceContract/Search
     * @param searchInsuranceContractRequest 
     */
    apiInsuranceContractSearchPost(searchInsuranceContractRequest?: SearchInsuranceContractRequest, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
