/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CULoanChargeModel } from '../model/models';
import { ResultAPI } from '../model/models';
import { SearchLoanChargeRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiLoanChargeGetByIdPostRequestParams {
    body?: string;
}

export interface ApiLoanChargeSavePostRequestParams {
    cULoanChargeModel?: CULoanChargeModel;
}

export interface ApiLoanChargeSearchPostRequestParams {
    searchLoanChargeRequest?: SearchLoanChargeRequest;
}


export interface LoanChargeProviderInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/LoanCharge/GetAll
*/
    apiLoanChargeGetAllGet(extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanCharge/GetById
* @param requestParameters
     */
    apiLoanChargeGetByIdPost(requestParameters: ApiLoanChargeGetByIdPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanCharge/Save
* @param requestParameters
     */
    apiLoanChargeSavePost(requestParameters: ApiLoanChargeSavePostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanCharge/Search
* @param requestParameters
     */
    apiLoanChargeSearchPost(requestParameters: ApiLoanChargeSearchPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
