/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CULoanContractModel } from '../model/models';
import { ResultAPI } from '../model/models';
import { SearchLoanContractRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface LoanContractServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/LoanContract/GetAll
     */
    apiLoanContractGetAllGet(extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContract/GetById
     * @param body 
     */
    apiLoanContractGetByIdPost(body?: string, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContract/Save
     * @param cULoanContractModel 
     */
    apiLoanContractSavePost(cULoanContractModel?: CULoanContractModel, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContract/Search
     * @param searchLoanContractRequest 
     */
    apiLoanContractSearchPost(searchLoanContractRequest?: SearchLoanContractRequest, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
