/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CULoanCollateralModel } from '../model/models';
import { ResultAPI } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiLoanCollateralDeletePostRequestParams {
    body?: string;
}

export interface ApiLoanCollateralGetByLoanContractPostRequestParams {
    body?: string;
}

export interface ApiLoanCollateralSavePostRequestParams {
    cULoanCollateralModel?: CULoanCollateralModel;
}


export interface LoanCollateralProviderInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/LoanCollateral/Delete
* @param requestParameters
     */
    apiLoanCollateralDeletePost(requestParameters: ApiLoanCollateralDeletePostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanCollateral/GetByLoanContract
* @param requestParameters
     */
    apiLoanCollateralGetByLoanContractPost(requestParameters: ApiLoanCollateralGetByLoanContractPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanCollateral/Save
* @param requestParameters
     */
    apiLoanCollateralSavePost(requestParameters: ApiLoanCollateralSavePostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
