/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ResultAPI } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiLoanContractAttachmentDownloadAttachmentIdGetRequestParams {
    attachmentId: string;
}

export interface ApiLoanContractAttachmentGetByLoanContractPostRequestParams {
    body?: string;
}

export interface ApiLoanContractAttachmentUploadPostRequestParams {
    loanContractId: string;
    file: Blob;
    note?: string;
}

export interface ApiLoanContractAttachmentViewPdfAttachmentIdGetRequestParams {
    attachmentId: string;
}


export interface LoanContractAttachmentProviderInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/LoanContractAttachment/Download/{attachmentId}
* @param requestParameters
     */
    apiLoanContractAttachmentDownloadAttachmentIdGet(requestParameters: ApiLoanContractAttachmentDownloadAttachmentIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContractAttachment/GetByLoanContract
* @param requestParameters
     */
    apiLoanContractAttachmentGetByLoanContractPost(requestParameters: ApiLoanContractAttachmentGetByLoanContractPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContractAttachment/Upload
* @param requestParameters
     */
    apiLoanContractAttachmentUploadPost(requestParameters: ApiLoanContractAttachmentUploadPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint get /api/LoanContractAttachment/ViewPdf/{attachmentId}
* @param requestParameters
     */
    apiLoanContractAttachmentViewPdfAttachmentIdGet(requestParameters: ApiLoanContractAttachmentViewPdfAttachmentIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
