/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CULoanProductModel } from '../model/models';
import { ResultAPI } from '../model/models';
import { SearchLoanProductRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiLoanProductGetByIdPostRequestParams {
    body?: string;
}

export interface ApiLoanProductSavePostRequestParams {
    cULoanProductModel?: CULoanProductModel;
}

export interface ApiLoanProductSearchPostRequestParams {
    searchLoanProductRequest?: SearchLoanProductRequest;
}


export interface LoanProductProviderInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/LoanProduct/GetAll
*/
    apiLoanProductGetAllGet(extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanProduct/GetById
* @param requestParameters
     */
    apiLoanProductGetByIdPost(requestParameters: ApiLoanProductGetByIdPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanProduct/Save
* @param requestParameters
     */
    apiLoanProductSavePost(requestParameters: ApiLoanProductSavePostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanProduct/Search
* @param requestParameters
     */
    apiLoanProductSearchPost(requestParameters: ApiLoanProductSearchPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
