/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AssignLoanContractRequest } from '../model/models';
import { CULoanContractModel } from '../model/models';
import { CancelLoanContractRequest } from '../model/models';
import { ChangeStatusRequest } from '../model/models';
import { GetOverdueListRequest } from '../model/models';
import { LoanCalculateRequest } from '../model/models';
import { ResultAPI } from '../model/models';
import { SearchLoanContractRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiLoanContractAssignPostRequestParams {
    assignLoanContractRequest?: AssignLoanContractRequest;
}

export interface ApiLoanContractCalculatePostRequestParams {
    loanCalculateRequest?: LoanCalculateRequest;
}

export interface ApiLoanContractCancelPostRequestParams {
    cancelLoanContractRequest?: CancelLoanContractRequest;
}

export interface ApiLoanContractChangeStatusPostRequestParams {
    changeStatusRequest?: ChangeStatusRequest;
}

export interface ApiLoanContractGetByIdPostRequestParams {
    body?: string;
}

export interface ApiLoanContractGetFinancialSummaryPostRequestParams {
    body?: string;
}

export interface ApiLoanContractGetOverdueListPostRequestParams {
    getOverdueListRequest?: GetOverdueListRequest;
}

export interface ApiLoanContractGetRepaymentSchedulePostRequestParams {
    body?: string;
}

export interface ApiLoanContractGetStatusHistoryPostRequestParams {
    body?: string;
}

export interface ApiLoanContractSavePostRequestParams {
    cULoanContractModel?: CULoanContractModel;
}

export interface ApiLoanContractSearchPostRequestParams {
    searchLoanContractRequest?: SearchLoanContractRequest;
}


export interface LoanContractProviderInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/LoanContract/Assign
* @param requestParameters
     */
    apiLoanContractAssignPost(requestParameters: ApiLoanContractAssignPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContract/Calculate
* @param requestParameters
     */
    apiLoanContractCalculatePost(requestParameters: ApiLoanContractCalculatePostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContract/Cancel
* @param requestParameters
     */
    apiLoanContractCancelPost(requestParameters: ApiLoanContractCancelPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContract/ChangeStatus
* @param requestParameters
     */
    apiLoanContractChangeStatusPost(requestParameters: ApiLoanContractChangeStatusPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint get /api/LoanContract/GetAll
*/
    apiLoanContractGetAllGet(extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContract/GetById
* @param requestParameters
     */
    apiLoanContractGetByIdPost(requestParameters: ApiLoanContractGetByIdPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContract/GetFinancialSummary
* @param requestParameters
     */
    apiLoanContractGetFinancialSummaryPost(requestParameters: ApiLoanContractGetFinancialSummaryPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContract/GetOverdueList
* @param requestParameters
     */
    apiLoanContractGetOverdueListPost(requestParameters: ApiLoanContractGetOverdueListPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContract/GetRepaymentSchedule
* @param requestParameters
     */
    apiLoanContractGetRepaymentSchedulePost(requestParameters: ApiLoanContractGetRepaymentSchedulePostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContract/GetStatusHistory
* @param requestParameters
     */
    apiLoanContractGetStatusHistoryPost(requestParameters: ApiLoanContractGetStatusHistoryPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContract/Save
* @param requestParameters
     */
    apiLoanContractSavePost(requestParameters: ApiLoanContractSavePostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContract/Search
* @param requestParameters
     */
    apiLoanContractSearchPost(requestParameters: ApiLoanContractSearchPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
