/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CULoanProductModel } from '../model/models';
import { ResultAPI } from '../model/models';
import { SearchLoanProductRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface LoanProductServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/LoanProduct/GetAll
     */
    apiLoanProductGetAllGet(extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanProduct/GetById
     * @param body 
     */
    apiLoanProductGetByIdPost(body?: string, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanProduct/Save
     * @param cULoanProductModel 
     */
    apiLoanProductSavePost(cULoanProductModel?: CULoanProductModel, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanProduct/Search
     * @param searchLoanProductRequest 
     */
    apiLoanProductSearchPost(searchLoanProductRequest?: SearchLoanProductRequest, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
