/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ResultAPI } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiLoanContractDocumentDeletePostRequestParams {
    body?: string;
}

export interface ApiLoanContractDocumentDownloadDocumentIdGetRequestParams {
    documentId: string;
}

export interface ApiLoanContractDocumentGetByLoanContractPostRequestParams {
    body?: string;
}

export interface ApiLoanContractDocumentUploadPostRequestParams {
    loanContractId: string;
    file: Blob;
    documentType: string;
    note?: string;
}

export interface ApiLoanContractDocumentViewDocumentIdGetRequestParams {
    documentId: string;
}


export interface LoanContractDocumentProviderInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/LoanContractDocument/Delete
* @param requestParameters
     */
    apiLoanContractDocumentDeletePost(requestParameters: ApiLoanContractDocumentDeletePostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint get /api/LoanContractDocument/Download/{documentId}
* @param requestParameters
     */
    apiLoanContractDocumentDownloadDocumentIdGet(requestParameters: ApiLoanContractDocumentDownloadDocumentIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContractDocument/GetByLoanContract
* @param requestParameters
     */
    apiLoanContractDocumentGetByLoanContractPost(requestParameters: ApiLoanContractDocumentGetByLoanContractPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/LoanContractDocument/Upload
* @param requestParameters
     */
    apiLoanContractDocumentUploadPost(requestParameters: ApiLoanContractDocumentUploadPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint get /api/LoanContractDocument/View/{documentId}
* @param requestParameters
     */
    apiLoanContractDocumentViewDocumentIdGet(requestParameters: ApiLoanContractDocumentViewDocumentIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
