/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CUPolicySettingModel } from '../model/models';
import { GetActivePolicyRequest } from '../model/models';
import { ResultAPI } from '../model/models';
import { SearchPolicySettingRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiPolicySettingGetActivePolicyPostRequestParams {
    getActivePolicyRequest?: GetActivePolicyRequest;
}

export interface ApiPolicySettingGetByIdPostRequestParams {
    body?: string;
}

export interface ApiPolicySettingSavePostRequestParams {
    cUPolicySettingModel?: CUPolicySettingModel;
}

export interface ApiPolicySettingSearchPostRequestParams {
    searchPolicySettingRequest?: SearchPolicySettingRequest;
}


export interface PolicySettingProviderInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/PolicySetting/GetActivePolicy
* @param requestParameters
     */
    apiPolicySettingGetActivePolicyPost(requestParameters: ApiPolicySettingGetActivePolicyPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint get /api/PolicySetting/GetAll
*/
    apiPolicySettingGetAllGet(extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/PolicySetting/GetById
* @param requestParameters
     */
    apiPolicySettingGetByIdPost(requestParameters: ApiPolicySettingGetByIdPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/PolicySetting/Save
* @param requestParameters
     */
    apiPolicySettingSavePost(requestParameters: ApiPolicySettingSavePostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/PolicySetting/Search
* @param requestParameters
     */
    apiPolicySettingSearchPost(requestParameters: ApiPolicySettingSearchPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
