/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CUPolicySettingModel } from '../model/models';
import { ResultAPI } from '../model/models';
import { SearchPolicySettingRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PolicySettingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/PolicySetting/GetAll
     */
    apiPolicySettingGetAllGet(extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/PolicySetting/GetById
     * @param body 
     */
    apiPolicySettingGetByIdPost(body?: string, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/PolicySetting/Save
     * @param cUPolicySettingModel 
     */
    apiPolicySettingSavePost(cUPolicySettingModel?: CUPolicySettingModel, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/PolicySetting/Search
     * @param searchPolicySettingRequest 
     */
    apiPolicySettingSearchPost(searchPolicySettingRequest?: SearchPolicySettingRequest, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
