/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BadDebtSummaryRequest } from '../model/models';
import { CustomerStatsRequest } from '../model/models';
import { MonthlyCashFlowRequest } from '../model/models';
import { ReportDateRangeRequest } from '../model/models';
import { ReportStoreRequest } from '../model/models';
import { ResultAPI } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiReportBadDebtSummaryPostRequestParams {
    badDebtSummaryRequest?: BadDebtSummaryRequest;
}

export interface ApiReportCollateralReportPostRequestParams {
    reportDateRangeRequest?: ReportDateRangeRequest;
}

export interface ApiReportCustomerAdvancedStatsPostRequestParams {
    reportDateRangeRequest?: ReportDateRangeRequest;
}

export interface ApiReportCustomerStatsPostRequestParams {
    customerStatsRequest?: CustomerStatsRequest;
}

export interface ApiReportDailyCollectionPostRequestParams {
    reportDateRangeRequest?: ReportDateRangeRequest;
}

export interface ApiReportEmployeeKpiPostRequestParams {
    reportDateRangeRequest?: ReportDateRangeRequest;
}

export interface ApiReportIncomeBreakdownPostRequestParams {
    reportDateRangeRequest?: ReportDateRangeRequest;
}

export interface ApiReportLoanPortfolioSummaryPostRequestParams {
    reportStoreRequest?: ReportStoreRequest;
}

export interface ApiReportMonthlyCashFlowPostRequestParams {
    monthlyCashFlowRequest?: MonthlyCashFlowRequest;
}

export interface ApiReportOutstandingLoansPostRequestParams {
    reportStoreRequest?: ReportStoreRequest;
}

export interface ApiReportOverdueSummaryPostRequestParams {
    reportStoreRequest?: ReportStoreRequest;
}


export interface ReportProviderInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/Report/BadDebtSummary
* @param requestParameters
     */
    apiReportBadDebtSummaryPost(requestParameters: ApiReportBadDebtSummaryPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Report/CollateralReport
* @param requestParameters
     */
    apiReportCollateralReportPost(requestParameters: ApiReportCollateralReportPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Report/CustomerAdvancedStats
* @param requestParameters
     */
    apiReportCustomerAdvancedStatsPost(requestParameters: ApiReportCustomerAdvancedStatsPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Report/CustomerStats
* @param requestParameters
     */
    apiReportCustomerStatsPost(requestParameters: ApiReportCustomerStatsPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Report/DailyCollection
* @param requestParameters
     */
    apiReportDailyCollectionPost(requestParameters: ApiReportDailyCollectionPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Report/EmployeeKpi
* @param requestParameters
     */
    apiReportEmployeeKpiPost(requestParameters: ApiReportEmployeeKpiPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Report/IncomeBreakdown
* @param requestParameters
     */
    apiReportIncomeBreakdownPost(requestParameters: ApiReportIncomeBreakdownPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Report/LoanPortfolioSummary
* @param requestParameters
     */
    apiReportLoanPortfolioSummaryPost(requestParameters: ApiReportLoanPortfolioSummaryPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Report/MonthlyCashFlow
* @param requestParameters
     */
    apiReportMonthlyCashFlowPost(requestParameters: ApiReportMonthlyCashFlowPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Report/OutstandingLoans
* @param requestParameters
     */
    apiReportOutstandingLoansPost(requestParameters: ApiReportOutstandingLoansPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Report/OverdueSummary
* @param requestParameters
     */
    apiReportOverdueSummaryPost(requestParameters: ApiReportOverdueSummaryPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
