/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CUStoreModel } from '../model/models';
import { ResultAPI } from '../model/models';
import { SearchStoreRequest } from '../model/models';
import { StoreDayLockRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiStoreGetByIdPostRequestParams {
    body?: string;
}

export interface ApiStoreLockDayPostRequestParams {
    storeDayLockRequest?: StoreDayLockRequest;
}

export interface ApiStoreSavePostRequestParams {
    cUStoreModel?: CUStoreModel;
}

export interface ApiStoreSearchPostRequestParams {
    searchStoreRequest?: SearchStoreRequest;
}

export interface ApiStoreUnlockDayPostRequestParams {
    storeDayLockRequest?: StoreDayLockRequest;
}


export interface StoreProviderInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/Store/GetAll
*/
    apiStoreGetAllGet(extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Store/GetById
* @param requestParameters
     */
    apiStoreGetByIdPost(requestParameters: ApiStoreGetByIdPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Store/LockDay
* @param requestParameters
     */
    apiStoreLockDayPost(requestParameters: ApiStoreLockDayPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Store/Save
* @param requestParameters
     */
    apiStoreSavePost(requestParameters: ApiStoreSavePostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Store/Search
* @param requestParameters
     */
    apiStoreSearchPost(requestParameters: ApiStoreSearchPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

    /**
     * 
     * 
     * @endpoint post /api/Store/UnlockDay
* @param requestParameters
     */
    apiStoreUnlockDayPost(requestParameters: ApiStoreUnlockDayPostRequestParams, extraHttpRequestParams?: any): Observable<ResultAPI>;

}
