/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CollectLoanPaymentModel { 
    loanContractId: string;
    purposes: Array<string>;
    reasonCode: string;
    amount: number;
    payerReceiverName?: string | null;
    description?: string | null;
}

