/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CUCustomerVisitModel { 
    visitId?: string | null;
    storeId: string;
    customerId: string;
    visitDate?: string;
    visitType: string;
    sourceType?: string | null;
    handledBy?: string | null;
    note?: string | null;
}

