/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CUCashVoucherModel { 
    voucherId?: string | null;
    storeId?: string | null;
    voucherType: string;
    reasonCode: string;
    businessDate?: string;
    voucherDatetime?: string;
    customerId?: string | null;
    loanContractId?: string | null;
    relatedVoucherId?: string | null;
    payerReceiverName?: string | null;
    payerReceiverAddress?: string | null;
    documentNo?: string | null;
    amount: number;
    description: string;
    isAdjustment?: boolean;
}

