/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CUCustomRoleModel { 
    customRoleId?: string | null;
    roleName?: string | null;
    description?: string | null;
    isActive?: boolean;
    storeId?: string | null;
}

