/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CUInsuranceContractModel { 
    insuranceContractId?: string | null;
    loanContractId: string;
    providerName: string;
    policyNumber?: string | null;
    insuranceName?: string | null;
    isMandatory?: boolean;
    premiumAmount?: number;
    coverageAmount?: number | null;
    effectiveFrom: string;
    effectiveTo?: string | null;
    statusCode?: string | null;
    note?: string | null;
}

