/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CULoanCollateralModel { 
    collateralId?: string | null;
    loanContractId?: string;
    collateralType?: string | null;
    description?: string | null;
    serialNumber?: string | null;
    estimatedValue?: number | null;
    detail?: string | null;
    note?: string | null;
}

