/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CULoanSettlementModel { 
    settlementId?: string | null;
    loanContractId: string;
    settlementType: string;
    requestDate?: string;
    settlementDate?: string | null;
    actualElapsedDays?: number;
    contractTotalDays?: number;
    completionRatio?: number;
    remainingPrincipalAmount?: number;
    accruedInterestAmount?: number;
    accruedPeriodicFeeAmount?: number;
    unpaidLatePenaltyAmount?: number;
    earlySettlementPenaltyAmount?: number;
    otherReceivableAmount?: number;
    discountAmount?: number;
    totalSettlementAmount?: number;
    note?: string | null;
}

