/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CULoanChargeModel { 
    chargeId?: string | null;
    loanContractId: string;
    scheduleId?: string | null;
    chargeCode: string;
    chargeName: string;
    chargeDate?: string;
    dueDate?: string;
    amount: number;
    note?: string | null;
}

