/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CULoanContractModel { 
    loanContractId?: string | null;
    storeId: string;
    customerId: string;
    loanProductId?: string | null;
    previousLoanContractId?: string | null;
    applicationDate?: string;
    termMonths: number;
    principalAmount: number;
    netDisbursedAmount?: number;
    interestRateMonthlySnapshot?: number;
    qlkvRateMonthlySnapshot?: number;
    qltsRateMonthlySnapshot?: number;
    fileFeeAmountSnapshot?: number;
    insuranceAmountSnapshot?: number;
    earlySettlementPenaltyRateSnapshot?: number;
    latePaymentPenaltyRateSnapshot?: number;
    latePaymentStartDaySnapshot?: number;
    badDebtStartDaySnapshot?: number;
    note?: string | null;
}

