/**
 * CrediFlow.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomerStatsRequest { 
    storeId?: string | null;
    fromDate?: string;
    toDate?: string;
    groupBy?: string | null;
}

